### ISSUE TITLE
How to update to GPT-3.5-turbo?

### ISSUE THREAD

**Issue by drakeonbr** [nextgrid/GPT-3-Nextjs-Tailwind-starter#4]
Hey bro, i'm testing some things on this repo and trying to learn more java from it and how the openai api works, how can I update it to GPT-3.5-turbo or GPT-4 instead of using GPT-3? Can you update it to GPT-4 in this repo or make another in GPT-4?

**Comment by ezzcodeezzlife** [comment]
Hey @drakeonbr,

Check out this Python boilerplate for GPT3.5 & 4: https://github.com/lablab-ai/openai-chat-endpoint-boilerplate
If you want Javascript you can check out: https://github.com/lablab-ai/chatgpt-clone-nodejs-express-react

**Comment by drakeonbr** [comment]
Thanks bro, but if I want to "update" this specific repo to gpt-3.5, is it possible? I'm having trouble doing this, would be grateful if you could help <3
